### PR TITLE
vse-carslab-managed refactor

### PR DESCRIPTION
**Pull request by jnunyez**
Aims at proposing a new clean structure to tackle the proper role for vse-carslab-managed repo. Moved all-things catalog-related (operators and day2 node optimizations) and argo related like ArgoAppSets out of scope of this repo. Scope is day2 configuration of workload clusters. Added a overlay file for volante cluster with the correspondent patches for sriov,ptp operators and rwn-optimizations. Requires merge of vse-catalog [PR20](https://github.com/redhat-partner-solutions/vse-catalog/pull/20)

### CODE REVIEW

**Review by natifridman — COMMENTED** [review]
Great work, looks much cleaner. Waiting for dependent PR to be merged

**Comment by natifridman** [comment]
@jnunyez Could you please try to squash commits to trigger the Github actions again?
Looks like I can't re-run it, maybe it's too old

**Comment by jnunyez** [comment]
@natifridman I believe it still requires to merge of vse-catalog https://github.com/redhat-partner-solutions/vse-catalog/pull/20

**Comment by natifridman** [comment]
> @natifridman I believe it still requires to merge of vse-catalog [redhat-partner-solutions/vse-catalog#20](https://github.com/redhat-partner-solutions/vse-catalog/pull/20)

Correct. Thanks for the reminder

**Comment by novacain1** [comment]
Reviewed and merged https://github.com/redhat-partner-solutions/vse-catalog/pull/20.  Could we look at this one again?

**Comment by natifridman** [comment]
@jnunyez Could you please rerun the action? Looks like I don't have permission...

**Comment by jnunyez** [comment]
I think the PR was too old. Only way to rerun the action for me was to add an empty commit. With the trigger of a fresh action run I could rerun manually the action. 
Looks ready for merge now.

**Review by natifridman — APPROVED** [review]
LGTM. I think we can have refinements later if needed

**Pull request merged**
